// All .gitignore templates for the GitignoreModal feature.
// Each export is a string for a specific tech stack or tool.

const templates = {
  node: `# Node.js\nnode_modules/\n.env\ndist/\nbuild/\n*.log\nnpm-debug.log*\nyarn-debug.log*\nyarn-error.log*\npackage-lock.json\npnpm-lock.yaml\n`,
  next: `# Next.js\n.next/\nout/\n`,
  react: `# React\n*.env.local\n*.env.development.local\n*.env.test.local\n*.env.production.local\n`,
  python: `# Python\n__pycache__/\n*.py[cod]\n*.pyo\n*.pyd\n.env\n.venv/\nvenv/\nENV/\nbuild/\ndist/\n*.egg-info/\n*.eggs/\npip-log.txt\npip-delete-this-directory.txt\n.tox/\n.coverage\n.pytest_cache/\n.mypy_cache/\n.dmypy.json\n.pyre/\npyrightconfig.json\n`,
  django: `# Django\n*.log\n*.pot\n*.pyc\n__pycache__/\nlocal_settings.py\ndb.sqlite3\nmedia/\nstaticfiles/\n`,
  flask: `# Flask\ninstance/\n.webassets-cache\n*.pyc\n__pycache__/\n.env\n`,
  vscode: `# VSCode\n.vscode/\n.history/\n`,
  intellij: `# IntelliJ IDEA\n.idea/\n*.iws\n*.iml\n*.ipr\n`,
  webstorm: `# WebStorm\n.idea/\n`,
  macos: `# macOS\n.DS_Store\n.AppleDouble\n.LSOverride\nIcon?\n._*\n.Spotlight-V100\n.Trashes\nehthumbs.db\n`,
  windows: `# Windows\nThumbs.db\nDesktop.ini\n$RECYCLE.BIN/\n`,
  linux: `# Linux\n*~\n.nfs*\n`,
  jetbrains: `# JetBrains IDEs\n.idea/\n*.iml\nout/\n`,
  angular: `# Angular\n.angular/\ndist/\ntmp/\n`,
  vue: `# Vue\n/dist/\n/node_modules/\n*.local\n`,
  svelte: `# Svelte\nnode_modules/\npublic/build/\n`,
  java: `# Java\n*.class\n*.jar\n*.war\n*.ear\ntarget/\nbin/\n.gradle/\nbuild/\n*.log\n*.javadoc\nhs_err_pid*\n.recommenders/\n.mvn/\n`,
  maven: `# Maven\ntarget/\npom.xml.tag\npom.xml.releaseBackup\npom.xml.versionsBackup\nrelease.properties\n`,
  gradle: `# Gradle\n.gradle/\nbuild/\n!gradle/wrapper/gradle-wrapper.jar\n`,
  rust: `# Rust\n/target/\n/Cargo.lock\n`,
  go: `# Go\n/bin/\n/pkg/\n/*.exe\n*.test\n*.out\nvendor/\n`,
  php: `# PHP\n/vendor/\ncomposer.lock\n.env\n.phpunit.result.cache\n`,
  laravel: `# Laravel\n/vendor/\n.env\n.phpunit.result.cache\n/storage/*.key\n/storage/logs/\n`,
  ruby: `# Ruby\n*.gem\n*.rbc\n.bundle/\n.config/\ncoverage/\nInstalledFiles\npkg/\nspec/reports/\ntest/tmp/\ntest/version_tmp/\ntmp/\n`,
  rails: `# Rails\n/log/*\n/tmp/*\n!/log/.keep\n!/tmp/.keep\n/storage/*\n!/storage/.keep\n/config/master.key\n/config/credentials.yml.enc\n/public/assets\n.byebug_history\n`,
  elixir: `# Elixir\n/_build/\n/deps/\n/erl_crash.dump\n.elixir_ls/\n`,
  dotnet: `# .NET\nbin/\nobj/\n*.user\n*.suo\n*.userosscache\n*.sln.docstates\n*.vs/\n`,
  unity: `# Unity\n[Ll]ibrary/\n[Tt]emp/\n[Oo]bj/\n[Bb]uild/\n[Bb]uilds/\nAssets/AssetStoreTools*\n*.csproj\n*.unityproj\n*.sln\n*.user\n*.pidb\n*.booproj\n*.svd\n*.pdb\n*.mdb\n`,
  android: `# Android\n.gradle/\nlocal.properties\n*.iml\nbuild/\ncaptures/\n.externalNativeBuild/\n.cxx/\n.idea/\noutput.json\n*.apk\n*.ap_\n`,
  ios: `# iOS/macOS\nbuild/\nDerivedData/\n*.pbxuser\n!default.pbxuser\n*.mode1v3\n*.mode2v3\n*.perspectivev3\nxcuserdata/\n*.xcuserstate\n*.moved-aside\n*.xcworkspace\n*.xcuserdatad\n`,
  docker: `# Docker\n**/.dockerignore\nDockerfile*\ndocker-compose*.yml\n.docker/\n`,
  terraform: `# Terraform\n*.tfstate\n*.tfstate.*\n.crash\n.terraform/\n.terraform.lock.hcl\n`,
  ansible: `# Ansible\n*.retry\n*.log\n`,
  kubernetes: `# Kubernetes\n*.yaml\n.kube/\n`,
  jupyter: `# Jupyter\n.ipynb_checkpoints\n`,
  notebooks: `# Notebooks\n*.ipynb\n.ipynb_checkpoints/\n`,
  markdown: `# Markdown\n*.md~\n`,
  logs: `# Logs\n*.log\nlogs/\nlog/\n`,
  tempfiles: `# Temp files\n*.tmp\n*.bak\n*.swp\n*~\n`,
  archives: `# Archives\n*.zip\n*.tar.gz\n*.rar\n*.7z\n*.gz\n*.bz2\n*.xz\n*.tgz\n`,
  images: `# Images\n*.png\n*.jpg\n*.jpeg\n*.gif\n*.svg\n*.ico\n`,
  videos: `# Videos\n*.mp4\n*.mov\n*.avi\n*.mkv\n`,
  fonts: `# Fonts\n*.ttf\n*.otf\n*.woff\n*.woff2\n`,
  configs: `# Configs\n*.env\n.env.*\n.secret\n.secrets/\n`,
  databases: `# Database files\n*.sqlite\n*.sqlite3\n*.db\n*.mdb\n`,
  androidstudio: `# Android Studio\n.idea/\n.gradle/\nbuild/\nlocal.properties\n*.iml\n`,
  eclipse: `# Eclipse\n.settings/\n.project\n.classpath\n`,
  netbeans: `# NetBeans\nnbproject/private/\nbuild/\nbbuild-impl.xml\nnbproject/Makefile-impl.mk\nnbproject/Makefile.mk\n`,
  electron: `# Electron\ndist-electron/\nbuild-electron/\n`,
  aws: `# AWS\n*.credentials\n.aws/\n`,
  gcloud: `# Google Cloud SDK\n.gcloud/\n`,
  r: `# R\n.Rhistory\n.RData\n.Rproj.user/\n`,
  julia: `# Julia\n*.jl.cov\n*.ji\n.julia/\n`,
  tensorflow: `# TensorFlow\n__pycache__/\n.pbtxt\ncheckpoint\nevents.out.tfevents.*\ngraph.pbtxt\n.saved_model/\n`,
  keras: `# Keras\n*.h5\n.vscode/\n`,
  latex: `# LaTeX\n*.aux\n*.lof\n*.log\n*.lot\n*.fls\n*.out\n*.toc\n*.fmt\n*.fot\n*.cb\n*.cb2\n*.synctex.gz\n*.fdb_latexmk\n`,
  blender: `# Blender\n*.blend1\n*.blend2\n__pycache__/\n`,
  photoshop: `# Photoshop\n*.psd\n*.psb\n*.tmp\n`,
  vagrant: `# Vagrant\n.vagrant/\n`,
  virtualbox: `# VirtualBox\n*.vbox\n*.vdi\n`,
  arduino: `# Arduino\n*.hex\n*.elf\n`,
  raspberry_pi: `# Raspberry Pi\n*.img\n`,
  npm: `# npm\npackage-lock.json\n`,
  yarn: `# Yarn\nyarn-error.log*\n.pnp.*\n`,
  pnpm: `# pnpm\npnpm-lock.yaml\n.node_modules/\n`,
  vault: `# HashiCorp Vault\n*.vault\n`,
  firestore: `# Google Firestore\n*.firebaserc\nfirebase-debug.log*\n`,
};

export default templates;
