import { db } from '@/server/db';
import { readReplicaDb2 } from '@/server/read-replica-2-db';
import { auth, clerkClient } from '@clerk/nextjs/server';
import { NextRequest, NextResponse } from 'next/server';

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { projectId, inviteToken } = body;

    if (!projectId || !inviteToken) {
      return NextResponse.json({ error: 'Missing projectId or inviteToken' }, { status: 400 });
    }

    const { userId } = await auth();
    if (!userId) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const client = await clerkClient();
    const user = await client.users.getUser(userId);

    // Check if user exists in database
    const dbUser = await db.user.findUnique({
      where: { id: userId },
    });

    const existingUserByEmail = await readReplicaDb2.user.findUnique({
      where: { emailAddress: user.emailAddresses[0]!.emailAddress },
    });

    // Create user if doesn't exist
    if (!dbUser && !existingUserByEmail) {
      return NextResponse.json({ error: 'User not found in the database' }, { status: 404 });
    }

    // Verify project and invite token
    const project = await readReplicaDb2.project.findUnique({
      where: { id: projectId },
      select: {
        id: true,
        name: true,
        inviteToken: true,
        invitationEnabled: true,
      },
    });

    if (!project) {
      return NextResponse.json({ error: 'Project not found' }, { status: 404 });
    }

    if (!inviteToken || project.inviteToken !== inviteToken || !project.invitationEnabled) {
      return NextResponse.json(
        {
          error:
            'Invalid or missing invite token. The link may have been regenerated by the project creator or the invitation feature may have been disabled by the project creator.',
        },
        { status: 400 },
      );
    }

    // Check if user is already a member
    try {
      const existingUserProject = await db.userToProject.findFirst({
        where: {
          userId,
          projectId,
        },
      });

      if (existingUserProject) {
        return NextResponse.json(
          { success: true, message: 'You are already a member of this project' },
          { status: 200 },
        );
      }
    } catch (findError) {
      console.error('Error checking existing membership:', findError);
      // Continue with join attempt - we'll handle duplicates in the catch block
    }

    // Add user to project
    try {
      await db.userToProject.create({
        data: {
          userId,
          projectId,
        },
      });
    } catch (createError: any) {
      // Handle unique constraint violation
      if (
        createError.code === 'P2002' ||
        (typeof createError.message === 'string' &&
          (createError.message.includes('Unique constraint') ||
            createError.message.includes('duplicate key') ||
            createError.message.includes('already exists')))
      ) {
        return NextResponse.json(
          { success: true, message: 'You are already a member of this project' },
          { status: 200 },
        );
      }
      throw createError; // Re-throw if it's not a duplicate error
    }

    return NextResponse.json(
      { success: true, message: 'Successfully joined the project!' },
      { status: 200 },
    );
  } catch (error: any) {
    console.error('Failed to join project:', {
      userId: await auth()
        .then((a) => a.userId)
        .catch(() => null),
      error,
    });

    return NextResponse.json({ error: 'Failed to join project' }, { status: 500 });
  }
}
